# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: encuesta.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'encuesta.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65ncuesta.proto\x12\x08\x65ncuesta\"\x93\x01\n\x14\x43rearEncuestaRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x0e\n\x06sector\x18\x03 \x01(\t\x12\x15\n\rnivel_escolar\x18\x04 \x01(\t\x12\x0f\n\x07latitud\x18\x05 \x01(\x01\x12\x10\n\x08longitud\x18\x06 \x01(\x01\x12\x13\n\x0b\x66oto_base64\x18\x07 \x01(\t\"-\n\x17ListarPorUsuarioRequest\x12\x12\n\nusuario_id\x18\x01 \x01(\t\"\xef\x01\n\x10\x45ncuestaResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x0e\n\x06nombre\x18\x03 \x01(\t\x12\x0e\n\x06sector\x18\x04 \x01(\t\x12\x15\n\rnivel_escolar\x18\x05 \x01(\t\x12\x0f\n\x07latitud\x18\x06 \x01(\x01\x12\x10\n\x08longitud\x18\x07 \x01(\x01\x12\x13\n\x0b\x66oto_base64\x18\x08 \x01(\t\x12\x12\n\nusuario_id\x18\t \x01(\t\x12\x16\n\x0eusuario_nombre\x18\n \x01(\t\x12\x16\n\x0e\x66\x65\x63ha_registro\x18\x0b \x01(\t\x12\x0e\n\x06\x65stado\x18\x0c \x01(\t\"G\n\x16ListaEncuestasResponse\x12-\n\tencuestas\x18\x01 \x03(\x0b\x32\x1a.encuesta.EncuestaResponse2\xb7\x01\n\x0f\x45ncuestaService\x12K\n\rCrearEncuesta\x12\x1e.encuesta.CrearEncuestaRequest\x1a\x1a.encuesta.EncuestaResponse\x12W\n\x10ListarPorUsuario\x12!.encuesta.ListarPorUsuarioRequest\x1a .encuesta.ListaEncuestasResponseB&\n\x13Pucmm.eict.edu.grpcB\rEncuestaProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'encuesta_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023Pucmm.eict.edu.grpcB\rEncuestaProtoP\001'
  _globals['_CREARENCUESTAREQUEST']._serialized_start=29
  _globals['_CREARENCUESTAREQUEST']._serialized_end=176
  _globals['_LISTARPORUSUARIOREQUEST']._serialized_start=178
  _globals['_LISTARPORUSUARIOREQUEST']._serialized_end=223
  _globals['_ENCUESTARESPONSE']._serialized_start=226
  _globals['_ENCUESTARESPONSE']._serialized_end=465
  _globals['_LISTAENCUESTASRESPONSE']._serialized_start=467
  _globals['_LISTAENCUESTASRESPONSE']._serialized_end=538
  _globals['_ENCUESTASERVICE']._serialized_start=541
  _globals['_ENCUESTASERVICE']._serialized_end=724
# @@protoc_insertion_point(module_scope)
