# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import encuesta_pb2 as encuesta__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in encuesta_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EncuestaServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearEncuesta = channel.unary_unary(
                '/encuesta.EncuestaService/CrearEncuesta',
                request_serializer=encuesta__pb2.CrearEncuestaRequest.SerializeToString,
                response_deserializer=encuesta__pb2.EncuestaResponse.FromString,
                _registered_method=True)
        self.ListarPorUsuario = channel.unary_unary(
                '/encuesta.EncuestaService/ListarPorUsuario',
                request_serializer=encuesta__pb2.ListarPorUsuarioRequest.SerializeToString,
                response_deserializer=encuesta__pb2.ListaEncuestasResponse.FromString,
                _registered_method=True)


class EncuestaServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CrearEncuesta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarPorUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EncuestaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearEncuesta': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearEncuesta,
                    request_deserializer=encuesta__pb2.CrearEncuestaRequest.FromString,
                    response_serializer=encuesta__pb2.EncuestaResponse.SerializeToString,
            ),
            'ListarPorUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarPorUsuario,
                    request_deserializer=encuesta__pb2.ListarPorUsuarioRequest.FromString,
                    response_serializer=encuesta__pb2.ListaEncuestasResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'encuesta.EncuestaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('encuesta.EncuestaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EncuestaService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CrearEncuesta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/encuesta.EncuestaService/CrearEncuesta',
            encuesta__pb2.CrearEncuestaRequest.SerializeToString,
            encuesta__pb2.EncuestaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarPorUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/encuesta.EncuestaService/ListarPorUsuario',
            encuesta__pb2.ListarPorUsuarioRequest.SerializeToString,
            encuesta__pb2.ListaEncuestasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
