plugins {
    id 'java'
    id 'application'
    id 'com.gradleup.shadow' version '9.4.2'
    id 'com.google.protobuf' version '0.9.4'
}

group = 'edu.pucmm.eict'
version = '1.0-SNAPSHOT'

application{
    mainClass = 'Pucmm.eict.edu.Main'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("io.javalin:javalin:7.2.2")
    implementation("org.slf4j:slf4j-simple:2.0.17")

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    implementation 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    implementation("com.fasterxml.jackson.core:jackson-databind:2.21.2")

    implementation 'dev.morphia.morphia:morphia-core:2.5.0'

    implementation 'org.mindrot:jbcrypt:0.4'

    runtimeOnly 'io.grpc:grpc-netty-shaded:1.75.0'
    implementation 'io.grpc:grpc-protobuf:1.62.2'
    implementation 'io.grpc:grpc-stub:1.62.2'
    implementation 'io.grpc:grpc-services:1.62.2' // Para habilitar la reflexión del servidor https://github.com/grpc/grpc-java/blob/master/documentation/server-reflection-tutorial.md#enable-server-reflection
    compileOnly 'org.apache.tomcat:annotations-api:6.0.53' // necessary for Java 9+
    implementation 'com.google.protobuf:protobuf-java:4.28.2'
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.25.1"
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.62.2'
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
    }

    //generatedFilesBaseDir = "$projectDir/generated"
}

shadowJar {
    archiveBaseName = 'app'
    archiveClassifier = ''
    archiveVersion = ''
}

test {
    useJUnitPlatform()
}